before_script:
  - hostname

# **********************************************************************
# NCRC
# **********************************************************************
.ncrcScript: &ncrcScript
  script:
    - source /opt/cray/pe/modules/default/init/bash
    - module use /ncrc/home2/fms/local/modulefiles
    - module load fre/bronx-12
    - module rm cray-netcdf cray-hdf5
    - module rm PrgEnv-intel PrgEnv-pgi PrgEnv-gnu PrgEnv-cray
    - module load PrgEnv-${COMP_FAMILY}
    - module swap ${COMP_NAME} ${COMP_NAME}/${COMP_VERSION}
    - module load cray-netcdf
    - module load cray-hdf5
    - list_paths -o pathnames_fms .
    - mkmf -m Makefile -p libfms_${myBuild}.a -t $FRE_COMMANDS_HOME/site/$FRE_SYSTEM_SITE/${COMP_mkTemplate}.mk -c "$CPPFLAGS" -Iinclude -Impp/include pathnames_fms
    - make $TARGET  libfms_${myBuild}.a

# **********************************************************************
# Intel 16 Compilers
# **********************************************************************
.build:ncrc:intel16:debug:
  stage: build
  tags:
    - ncrc
  variables:
    COMP_FAMILY: intel
    COMP_NAME: intel
    COMP_VERSION: 16.0.3.210
    COMP_mkTemplate: intel
    TARGET: OPENMP=on DEBUG=on
    CPPFLAGS: "-Duse_netCDF -Duse_libMPI -DINTERNAL_FILE_NML"
    myBuild: ncrc_intel16_debug
  <<: *ncrcScript
  artifacts:
    paths:
      - libfms_${myBuild}.a
      - ./*.mod

.build:ncrc:intel16:repro:
  stage: build
  tags:
    - ncrc
  variables:
    COMP_FAMILY: intel
    COMP_NAME: intel
    COMP_VERSION: 16.0.3.210
    COMP_mkTemplate: intel
    TARGET: OPENMP=on REPRO=on
    CPPFLAGS: "-Duse_netCDF -Duse_libMPI -DINTERNAL_FILE_NML"
    myBuild: ncrc_intel16_repro
  <<: *ncrcScript
  artifacts:
    paths:
      - libfms_${myBuild}.a
      - ./*.mod

.build:ncrc:intel16:prod:
  stage: build
  tags:
    - ncrc
  variables:
    COMP_FAMILY: intel
    COMP_NAME: intel
    COMP_VERSION: 16.0.3.210
    COMP_mkTemplate: intel
    TARGET: OPENMP=on
    CPPFLAGS: "-Duse_netCDF -Duse_libMPI -DINTERNAL_FILE_NML"
    myBuild: ncrc_intel16_prod
  <<: *ncrcScript
  artifacts:
    paths:
      - libfms_${myBuild}.a
      - ./*.mod

# **********************************************************************
# GNU Compilers
# **********************************************************************
.build:ncrc:gnu:debug:
  stage: build
  tags:
    - ncrc
  variables:
    COMP_FAMILY: gnu
    COMP_NAME: gcc
    COMP_VERSION: 5.3.0
    COMP_mkTemplate: gnu
    TARGET: DEBUG=on
    CPPFLAGS: "-Duse_netCDF -Duse_libMPI -DINTERNAL_FILE_NML -D_F2000"
    myBuild: ncrc_gnu_debug
  <<: *ncrcScript
  artifacts:
    paths:
      - libfms_${myBuild}.a
      - ./*.mod

.build:ncrc:gnu:repro:
  stage: build
  tags:
    - ncrc
  variables:
    COMP_FAMILY: gnu
    COMP_NAME: gcc
    COMP_VERSION: 5.3.0
    COMP_mkTemplate: gnu
    TARGET: OPENMP=on REPRO=on
    CPPFLAGS: "-Duse_netCDF -Duse_libMPI -DINTERNAL_FILE_NML -D_F2000"
    myBuild: ncrc_gnu_repro
  <<: *ncrcScript
  artifacts:
    paths:
      - libfms_${myBuild}.a
      - ./*.mod

.build:ncrc:gnu:prod:
  stage: build
  tags:
    - ncrc
  variables:
    COMP_FAMILY: gnu
    COMP_NAME: gcc
    COMP_VERSION: 5.3.0
    COMP_mkTemplate: gnu
    TARGET: OPENMP=on
    CPPFLAGS: "-Duse_netCDF -Duse_libMPI -DINTERNAL_FILE_NML -D_F2000"
    myBuild: ncrc_gnu_prod
  <<: *ncrcScript
  artifacts:
    paths:
      - libfms_${myBuild}.a
      - ./*.mod

# **********************************************************************
# PGI Compilers
# **********************************************************************
.build:ncrc:pgi:debug:
  stage: build
  tags:
    - ncrc
  variables:
    COMP_FAMILY: pgi
    COMP_NAME: pgi
    COMP_VERSION: 17.7.0
    COMP_mkTemplate: pgi
    TARGET: OPENMP=on DEBUG=on
    CPPFLAGS: "-Duse_netCDF -Duse_libMPI -DINTERNAL_FILE_NML"
    myBuild: ncrc_pgi_debug
  <<: *ncrcScript
  artifacts:
    paths:
      - libfms_${myBuild}.a
      - ./*.mod

.build:ncrc:pgi:repro:
  stage: build
  tags:
    - ncrc
  variables:
    COMP_FAMILY: pgi
    COMP_NAME: pgi
    COMP_VERSION: 17.7.0
    COMP_mkTemplate: pgi
    TARGET: OPENMP=on REPRO=on
    CPPFLAGS: "-Duse_netCDF -Duse_libMPI -DINTERNAL_FILE_NML"
    myBuild: ncrc_pgi_repro
  <<: *ncrcScript
  artifacts:
    paths:
      - libfms_${myBuild}.a
      - ./*.mod

.build:ncrc:pgi:prod:
  stage: build
  tags:
    - ncrc
  variables:
    COMP_FAMILY: pgi
    COMP_NAME: pgi
    COMP_VERSION: 17.7.0
    COMP_mkTemplate: pgi
    TARGET: OPENMP=on
    CPPFLAGS: "-Duse_netCDF -Duse_libMPI -DINTERNAL_FILE_NML"
    myBuild: ncrc_pgi_prod
  <<: *ncrcScript
  artifacts:
    paths:
      - libfms_${myBuild}.a
      - ./*.mod

# **********************************************************************
# Cray Compilers
# **********************************************************************
.build:ncrc:cce:debug:
  stage: build
  tags:
    - ncrc
  variables:
    COMP_FAMILY: cray
    COMP_NAME: cce
    COMP_VERSION: 8.5.0
    COMP_mkTemplate: cce
    TARGET: OPENMP=on DEBUG=on
    CPPFLAGS: "-Duse_netCDF -Duse_libMPI -DINTERNAL_FILE_NML -D_F2000"
    myBuild: ncrc_cce_debug
  <<: *ncrcScript
  artifacts:
    paths:
      - libfms_${myBuild}.a
      - ./*.mod

.build:ncrc:cce:repro:
  stage: build
  tags:
    - ncrc
  variables:
    COMP_FAMILY: cray
    COMP_NAME: cce
    COMP_VERSION: 8.5.0
    COMP_mkTemplate: cce
    TARGET: OPENMP=on REPRO=on
    CPPFLAGS: "-Duse_netCDF -Duse_libMPI -DINTERNAL_FILE_NML -D_F2000"
    myBuild: ncrc_cce_repro
  <<: *ncrcScript
  artifacts:
    paths:
      - libfms_${myBuild}.a
      - ./*.mod

.build:ncrc:cce:prod:
  stage: build
  tags:
    - ncrc
  variables:
    COMP_FAMILY: cray
    COMP_NAME: cce
    COMP_VERSION: 8.5.0
    COMP_mkTemplate: cce
    TARGET: OPENMP=on
    CPPFLAGS: "-Duse_netCDF -Duse_libMPI -DINTERNAL_FILE_NML -D_F2000"
    myBuild: ncrc_cce_prod
  <<: *ncrcScript
  artifacts:
    paths:
      - libfms_${myBuild}.a
      - ./*.mod

# **********************************************************************
# Google Compute
# **********************************************************************
.gcpScript: &gcpScript
  script:
    - source /apps/lmod/lmod/init/sh
    - module load intel/19.0.1.144
    - module load mpich/3.3
    - module load netcdf/4.6.2
    - module load netcdf-fortran/4.4.4
    - envg
    - autoreconf -i
    - ./configure
    - make distcheck

build:gcp:intel:
  stage: build
  tags:
    - gfdl-gcp
  variables:
    CC: mpicc
    FC: mpif90
    CPPFLAGS: "-I/apps/spack/opt/spack/linux-centos7-x86_64/intel-19.0.1.144/netcdf-4.6.2-iq53f4shh2qy4f7tmurxxyjzhxhxpjxd/include -I/apps/spack/opt/spack/linux-centos7-x86_64/intel-19.0.1.144/hdf5-1.8.16-romz4gqlhno57t5oc4qym24w7arkk7i7/include -I/apps/spack/opt/spack/linux-centos7-x86_64/intel-19.0.1.144/netcdf-fortran-4.4.4-p23ncwfcytdjtwykkvacvhdpweo4vhvr/include"
    FCFLAGS: "-fno-alias -stack_temps -safe_cray_ptr -ftz -assume byterecl -i4 -r8 -nowarn -g -sox -traceback"
  <<: *gcpScript