name: libFMS tests

on: [push, pull_request]

jobs:
  whitespace:
    runs-on: ubuntu-latest
    steps:
      - name: Check code
        uses: actions/checkout@v2
      - name: Check for trailing white spaces
        id: twspace
        run: |
          find . -type f -not -path "./.git/*" -exec egrep -l " +$" {} \; | tee files_trailwspace.txt
          echo "::set-output name=nfiles::$(wc -l files_trailwspace.txt | awk '{print $1}')"
      - name: Check Fortran for tabs
        id: ftntab
        run: |
          find . -type f -and \( -name \*.INC -or -name \*.inc -or \
                                 -name \*.fh -or -name \*.FH -or \
                                 -name \*.\[fF\]90 -or -name \*.\[fF\] \) \
                                 -exec grep -l $'\t' {}  \; | tee files_tabs.txt
          echo "::set-output name=nfiles::$(wc -l files_tabs.txt | awk '{print $1}')"
      - name: Check for Failure
        run: |
          if test ${{ steps.twspace.outputs.nfiles }} -gt 0
          then
            echo "::error::One or more files have trailing white space or one or more Fortran files have tab characters"
            cat files_trailwspace.txt
          fi
          if test ${{ steps.ftntab.outputs.nfiles }} -gt 0
          then
            echo "::error::${{steps.ftntab.outputs.nfiles}} Fortran files contain tab characters."
            cat files_tabs.txt
          fi
#      - name: Report Artifacts
#        uses: actions/upload-artifact@v1
#        if: failure()
#        with:
#          name: non-compliant-files
#          path: files_*.txt
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distcheck-conf-flags: [--enable-openmp, --disable-openmp, --enable-mixed-mode, --disable-setting-flags]
        fcflags: ["-I/usr/include", "-fdefault-real-8 -fdefault-double-8 -fcray-pointer -ffree-line-length-none -I/usr/include"]
        exclude:
          - distcheck-conf-flags: --disable-setting-flags
            fcflags: -I/usr/include
          - distcheck-conf-flags: --enable-mixed-mode
            fcflags: "-fdefault-real-8 -fdefault-double-8 -fcray-pointer -ffree-line-length-none -I/usr/include"
    container:
      image: underwoo/ubuntu_libfms_gnu
      env:
        FCFLAGS: "${{ matrix.fcflags }}"

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Prepare GNU autoconf for build
      run: autoreconf -if
    - name: Configure the build
      run: ./configure ${{ matrix.distcheck-conf-flags }}
      env:
        DISTCHECK_CONFIGURE_FLAGS: "${{ matrix.distcheck-conf-flags }}"
    - name: Build the library
      run: make -j distcheck
