name: Build libFMS test with autotools

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        conf-flags: [--disable-openmp, --enable-mixed-mode, --disable-setting-flags, --with-mpi=no]
        yaml-flag:  [--with-yaml, ""]
    container:
      image: noaagfdl/ubuntu_libfms_gnu
      env:
        TEST_VERBOSE: 1
        DISTCHECK_CONFIGURE_FLAGS: "${{ matrix.conf-flags }} ${{ matrix.yaml-flag }}"
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Prepare GNU autoconf for build
      run: autoreconf -if
    - name: Configure the build
      if: ${{ matrix.conf-flags != '--disable-setting-flags' }}
      run: ./configure  ${DISTCHECK_CONFIGURE_FLAGS}
    - name: Configure the build with compiler flags
      if: ${{ matrix.conf-flags == '--disable-setting-flags' }}
      run: ./configure  ${DISTCHECK_CONFIGURE_FLAGS}
      env:
        FCFLAGS: "-fdefault-real-8 -fdefault-double-8 -fcray-pointer -ffree-line-length-none -I/usr/include"
    - name: Build the library
      run: make -j distcheck
      if: ${{ matrix.conf-flags != '--with-mpi=no' }}
    - name: Build the library (without test suite for serial build)
      run: make
      if: ${{ matrix.conf-flags == '--with-mpi=no' }}
