name: Tag CI libFMS and AM4 regression
  
on:
   push:
        tags:
             - '*alpha*'
             - '*beta*'
   workflow_dispatch:
jobs:
   parallelWorks:
    runs-on: [self-hosted, pw-platform]
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        include:
                - runname: FMS with intel 18
                  runscript: python3 /home/Thomas.Robinson/pw/storage/pw_api_python/FMStestStartClusters.py azcluster_noaa
                - runname: FMS with intel 2021 container
                  runscript: python3 /home/Thomas.Robinson/pw/storage/pw_api_python/FMSintel21StartClusters.py azcluster_noaa_two
                - runname: AM4 regression
                  runscript: python3 /home/Thomas.Robinson/pw/storage/pw_api_python/AM4_intel21StartClusters.py azcluster_noaa

    steps:
                - name: FMS make check on paralellWorks
                  env:
                          RUNNAME: ${{ matrix.runname }}
                          RUNSCRIPT: ${{ matrix.runscript }}
                  run: $RUNSCRIPT
   ShutDownCluster:
    runs-on: [self-hosted, pw-platform]
    if: always()
    needs: [parallelWorks]
    strategy:
      matrix:
        include:
                - cluster: azcluster_noaa
                - cluster: azcluster_noaa_two
    steps:
                - name: Turn off cluster
                  env:
                          CLUSTER: ${{ matrix.cluster }}
                  run: python3 /home/Thomas.Robinson/pw/storage/pw_api_python/stopClusters.py $CLUSTER
