name: Test coupler build
on: [push, pull_request]

jobs:
  coupler-build:
    runs-on: ubuntu-latest
    container:
      image: noaagfdl/ubuntu_libfms_gnu
      env:
        FCFLAGS: "-I/usr/include" 
        VERBOSE: 1
    steps:
    - name: Checkout FMScoupler
      uses: actions/checkout@v2
      with:
        repository: 'NOAA-GFDL/FMScoupler'
    - name: Test Null build
      run: t/null_model_build.sh
