name: Test coupler build
on: [pull_request]

jobs:
  coupler-build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/noaa-gfdl/fms/fms-ci-rocky-gnu:12.3.0
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
      env:
        CC: mpicc
        FC: mpif90
        CPPFLAGS: '-I/opt/view/include -Duse_LARGEFILE -DMAXFIELDMETHODS_=500'
        FCFLAGS: '-fallow-argument-mismatch -fcray-pointer -fdefault-double-8 -fdefault-real-8 -Waliasing -ffree-line-length-none -fno-range-check -I/opt/view/include'
        LDFLAGS: '-L/opt/view/lib'
        VERBOSE: 1
    steps:
    - name: Checkout FMS
      uses: actions/checkout@v2
      with:
        path: FMS
    - name: Checkout FMScoupler
      uses: actions/checkout@v2
      with:
        repository: 'NOAA-GFDL/FMScoupler'
        path: FMScoupler
    - name: Test Null build
      run: FMScoupler/t/null_model_build.sh --local-fms
