name: Run MOM6 test suite

# runs on PR's or when manually triggered
on: [workflow_dispatch, pull_request]

# cancel running jobs if theres a newer push
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/noaa-gfdl/fms/fms-ci-rocky-gnu:12.3.0
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
    - name: Checkout MOM6 repository
      uses: actions/checkout@v4
      with:
        repository: 'NOAA-GFDL/MOM6'
        submodules: recursive
    - name: Build FMS and MOM test suite
      run: |
        cd .testing
        make -j
      env:
        FMS_COMMIT: $GITHUB_SHA
    - name: Run MOM tests
      run: make -j test
